LAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('user.urls', namespace='user')),
    path('pupils/', include('pupils.urls', namespace='pupils')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('reports/', include('reports.urls', namespace='reports')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.view_404'
handler403 = 'main.views.view_403'
handler500 = 'main.views.view_500'

reports/urls.py
from django.urls import path

from reports import views

app_name = 'reports'

urlpatterns = [
    path('', views.ReportsListView.as_view(), name='reports_list'),
    path('create-report/', views.CreateReportView.as_view(), name='create_report'),
    path('read-report/<int:report_id>/', views.ReadReportView.as_view(), name='read_report'),
    path('update-report/<int:report_id>/', views.UpdateReportView.as_view(), name='update_report'),
    path('delete-report/<int:report_id>/', views.DeleteReportView.as_view(), name='delete_report'),
    path('get-report-period/<int:report_id>/', views.GetReportPeriod.as_view(), name='get_report_period'),
    path('save-report-as-pdf/<int:report_id>/', views.SaveReportAsPdf.as_view(), name='save_report_as_pdf'),
    path('save-report-as-png/<int:report_id>/', views.SaveReportAsPng.as_view(), name='save_report_as_png'),
]

reports/models.py
import datetime

from django.db import models
from django.urls import reverse

from pupils.models import Pupil

class Report(models.Model):
    """Модель описания отчёта"""
    pupil = models.ForeignKey(verbose_name='Ученик', to=Pupil, on_delete=models.CASCADE, related_name='reports_pupil')
    start_period = models.DateField(verbose_name='Начало периода', auto_now_add=False)
    end_period = models.DateField(verbose_name='Конец периода', default=datetime.date.today)

    def __str__(self):
        return f"{self.pupil} - с {self.start_period.strftime('%d %b %Y')} по {self.end_period.strftime('%d %b %Y')}"
    
    def get_absolute_url(self):
        return reverse("reports:read_report", kwargs={"report_id": self.pk})
    
    class Meta:
        db_table = 'reports'
        verbose_name = 'Отчёт'
        verbose_name_plural = 'Отчёты'
        ordering = ('-id',)
    
    

reports/forms.py
from django import forms

from reports.models import Report

from pupils.models import Pupil


class ReportsFilterForm(forms.ModelForm):
    """Класс формы фильтрации отчётов"""
    class Meta:
        model = Report
        fields = '__all__'
        widgets = {
            'pupil': forms.Select(attrs={'class': 'form-select'}),
            'start_period': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': '2024-01-01'}),
            'end_period': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': '2024-01-01'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None) 
        super(ReportsFilterForm, self).__init__(*args, **kwargs)

        self.fields['pupil'].queryset = Pupil.objects.filter(owner=self.user, is_active=True)
        self.fields['pupil'].empty_label = 'Выбери ученика'
        self.fields['pupil'].required = False

        self.fields['start_period'].required = False

        self.fields['end_period'].required = False


class CreateReportForm(forms.ModelForm):
    """Класс формы создания отчётов"""
    class Meta:
        model = Report
        fields = '__all__'
        widgets = {
            'pupil': forms.Select(attrs={'class': 'form-select'}),
            'start_period': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': '2024-01-01'}),
            'end_period': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': '2024-01-01'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None) 
        super(CreateReportForm, self).__init__(*args, **kwargs)

        self.fields['pupil'].queryset = Pupil.objects.filter(owner=self.user, is_active=True)
        self.fields['pupil'].empty_label = 'Выбери ученика'


class UpdateReportForm(forms.ModelForm):
    """Класс формы обновления данных отчёта"""
    class Meta:
        model = Report
        fields = '__all__'
        widgets = {
            'pupil': forms.Select(attrs={'class': 'form-select'}),
            'start_period': forms.DateInput(attrs={'class': 'form-control start-period-updater', 'type': 'date', 'placeholder': '2024-01-01'}),
            'end_period': forms.DateInput(attrs={'class': 'form-control end-period-updater', 'type': 'date', 'placeholder': '2024-01-01'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None) 
        super(UpdateReportForm, self).__init__(*args, **kwargs)

        self.fields['pupil'].queryset = Pupil.objects.filter(owner=self.user, is_active=True)
        self.fields['pupil'].empty_label = 'Выбери ученика'

reports/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse, Http404, JsonResponse
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from transliterate import slugify

from reports.models import Report

from reports.forms import ReportsFilterForm, CreateReportForm, UpdateReportForm

from reports.utils import generate_pdf, generate_png

from user.utils import verify_owner


class ReportsListView(LoginRequiredMixin, ListView):
    """Класс представления для страницы со списком отчётов"""
    template_name = 'reports/reports_list.html'
    context_object_name = 'reports'
    paginate_by = 5

    def get_queryset(self):
        reports = Report.objects.filter(pupil__owner=self.request.user).select_related('pupil')

        pupil = self.request.GET.get('pupil', None)

        start_period = self.request.GET.get('start_period', None)

        end_period = self.request.GET.get('end_period', None)

        if pupil:
            reports = reports.filter(pupil__id=pupil)

        if start_period:
            reports = reports.filter(start_period__gte=start_period)

        if end_period:
            reports = reports.filter(end_period__lte=end_period)

        return reports

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # при создании формы передаём в неё пользователя
        context['form'] = ReportsFilterForm(data=self.request.GET, user=self.request.user) 
        context['title'] = 'L.A.S - Отчёты'
        return context


class CreateReportView(LoginRequiredMixin, CreateView):
    """Класс представления для страницы создания отчёта"""
    template_name = 'reports/create_report.html'
    form_class = CreateReportForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'L.A.S - Создать отчёт'
        return context
    
    def get_form_kwargs(self):
        kwargs = super(CreateReportView, self).get_form_kwargs()
        # при создании формы передаём в неё пользователя
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        return super().form_valid(form)


class ReadReportView(LoginRequiredMixin, DetailView):
    """Класс представления для страницы просмотра отчёта"""
    template_name = 'reports/read_report.html'
    context_object_name = 'report'
    model = Report
    pk_url_kwarg = 'report_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'L.A.S - Просмотр отчёта'
        return context
    
    def get_object(self, report_id=None, queryset=None):
        try:
            if report_id is None:
                report_id = self.kwargs.get(self.pk_url_kwarg)

            report = Report.objects.get(id=report_id)
        except Report.DoesNotExist:
            report = None
        finally:
            return report
    
    def get(self, request, report_id, *args, **kwargs):
        report = self.get_object(report_id)

        if report is not None:
            if verify_owner(report.pupil.owner, self.request.user):
                return super().get(request, report_id, *args, **kwargs)
            else:
                raise PermissionDenied()
        raise Http404()


class UpdateReportView(LoginRequiredMixin, UpdateView):
    """Класс представления для страницы обновления данных отчёта"""
    template_name = 'reports/update_report.html'
    form_class = UpdateReportForm
    model = Report
    context_object_name = 'report'
    pk_url_kwarg = 'report_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'L.A.S - Обновить данные отчёта'
        return context
    
    def get_form_kwargs(self):
        kwargs = super(UpdateReportView, self).get_form_kwargs()
        # при создании формы передаём в неё пользователя
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        return super().form_valid(form)
    
    def get_object(self, report_id=None, queryset=None):
        try:
            if report_id is None:
                report_id = self.kwargs.get(self.pk_url_kwarg)

            report = Report.objects.get(id=report_id)
        except Report.DoesNotExist:
            report = None
        finally:
            return report
    
    def get(self, request, report_id, *args, **kwargs):
        report = self.get_object(report_id)

        if report is not None:
            if verify_owner(report.pupil.owner, self.request.user):
                return super().get(request, report_id, *args, **kwargs)
            else:
                raise PermissionDenied()
        raise Http404()

    def post(self, request, report_id, *args, **kwargs):
        report = self.get_object(report_id)

        if report is not None:
            if verify_owner(report.pupil.owner, self.request.user):
                return super().post(request, report_id, *args, **kwargs)
            else:
                raise PermissionDenied()
        raise Http404()

class DeleteReportView(LoginRequiredMixin, DeleteView):
    """Класс представления для удаления отчёта"""
    model = Report
    success_url = reverse_lazy('reports:reports_list')
    pk_url_kwarg = 'report_id'
    
    def get_object(self, report_id=None, queryset=None):
        try:
            if report_id is None:
                report_id = self.kwargs.get(self.pk_url_kwarg)

            report = Report.objects.get(id=report_id)
        except Report.DoesNotExist:
            report = None
        finally:
            return report
    
    def post(self, request, report_id, *args, **kwargs):
        report = self.get_object(report_id)

        if report is not None:
            if verify_owner(report.pupil.owner, self.request.user):
                return super().post(request, report_id, *args, **kwargs)
            else:
                raise PermissionDenied()
        raise Http404()
    

class GetReportPeriod(LoginRequiredMixin, View):
    """Класс представления для получения периода отчёта"""
    def get_object(self, report_id=None, queryset=None):
        try:
            if report_id is None:
                report_id = self.kwargs.get(self.pk_url_kwarg)

            report = Report.objects.get(id=report_id)
        except Report.DoesNotExist:
            report = None
        finally:
            return report
    
    def get(self, request, report_id):
        report = self.get_object(report_id)

        if report is not None:
            response_data = {
                'start_period': report.start_period,
                'end_period': report.end_period
                }

            return JsonResponse(response_data)
        else:
            raise Http404()


class SaveReportAsPdf(View):
    """Класс представления для сохранения отчёта в формате pdf"""
    def get_object(self, report_id=None, queryset=None):
        try:
            if report_id is None:
                report_id = self.kwargs.get(self.pk_url_kwarg)

            report = Report.objects.get(id=report_id)
        except Report.DoesNotExist:
            report = None
        finally:
            return report
    
    def get(self, request, report_id):
        report = self.get_object(report_id)

        if report is not None:
            pdf_file = generate_pdf(report, request)

            filename = slugify(str(report))

            response = HttpResponse(pdf_file, content_type='application/pdf', headers={
                'Content-Disposition': f'attachment; filename="{filename}.pdf"'
            })

            return response
        else:
            raise Http404()


class SaveReportAsPng(View):
    """Класс представления для сохранения отчёта в формате png"""
    def get_object(self, report_id, queryset=None):
        return Report.objects.get(id=report_id)
    
    def get(self, request, report_id):
        report = self.get_object(report_id)

        png_file = generate_png(report)

        filename = slugify(str(report))

        response = HttpResponse(png_file, content_type='image/png', headers={
            'Content-Disposition': f'attachment; filename="{filename}.png"'
        })

        return response

reports/templates/reports/create_report.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block additional_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock  %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2 text-center">Добавить отчёт</h2>
    <form action="{% url "reports:create_report" %}" method="post" class="form">
      {% csrf_token %}
      {% draw_form form %}
      <div class="form__item text-center">
        <button class="btn btn-success" type="submit">Добавить</button>
      </div>
    </form>
  </section>
</div>
{% endblock %}

{% block additional_scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>
<script src="{% static "assets/js/datepikers.js" %}"></script>
{% endblock  %}

reports/templates/reports/read_report.html
{% extends "base.html" %}

{% load static %}

{% load reports_tags %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2 text-center">Отчёт</h2>
    <p class="section__text">{{ report }}:</p>
    {% report_lessons report.pupil.id report.start_period report.end_period %}
    <a href="{% url "reports:save_report_as_png" report.id %}" class="btn btn-primary" download><i class="fa-solid fa-download icon"></i>Сохранить в PNG</a>
  </section>
</div>
{% endblock %}

reports/templates/reports/reports_list.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block additional_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-3 col-sm-12">
    <div class="offcanvas-lg offcanvas-start" tabindex="-1" id="filter" aria-labelledby="filterLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#filter"
          aria-label="Close"></button>
      </div>
      <div class="offcanvas-body flex-column">
        <h3>Фильтр</h3>
        <form action="{% url "reports:reports_list" %}" method="get" class="form">
          {% draw_form form %}
          <div class="form__item text-center">
            <button class="btn btn-primary" type="submit">Применить</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col-lg-9 col-sm-12">
    <h2>Список отчётов</h2>
    <div class="togglers">
      <a href="{% url "reports:create_report" %}" class="btn btn-success"><i class="fa-solid fa-plus"></i> Добавить</a>
      <button data-bs-toggle="offcanvas" data-bs-target="#filter" role="button" class="btn btn-secondary btn_filter"
        aria-controls="filter"><i class="fa-solid fa-filter"></i> Фильтр</button>
    </div>
    <div class="cards row g-3">
      {% if reports %}
      {% for report in reports %}
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ report.pupil }}</h5>
          <p class="card-text">Период проведения уроков: с {{ report.start_period }} по {{ report.end_period }}</p>
          <a href="{{ report.get_absolute_url }}" class="card-link">Открыть</a>
          <a href="{% url "reports:update_report" report.id %}" class="card-link">Редактировать</a>
        </div>
      </div>
      {% endfor %}

      {% pagination page_obj paginator %}

      {% else %}
      <h3>Ничего не найдено!</h3>
      {% endif %}

    </div>
  </div>
</div>
{% endblock %}

{% block additional_scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>
<script src="{% static "assets/js/datepikers.js" %}"></script>
{% endblock %}

reports/templates/reports/update_report.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block additional_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock  %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2 text-center">Обновить данные отчёта</h2>
    <form action="{% url "reports:update_report" report.id %}" method="post" class="form">
      {% csrf_token %}
      {% draw_form form %}
      <div class="form__item text-center">
        <button class="btn btn-primary" type="submit">Обновить</button>
      </div>
    </form>
  </section>

  <section class="section">
    <h2 class="section__h2">Удалить отчёт</h2>
    <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deletereport" role="button">Удалить</button>
  </section>
</div>

<div class="modal fade" id="deletereport" tabindex="-1" aria-labelledby="deletereportLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deletereportLabel">Удалить отчёт</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Вы действительно хотите удалить {{ report }}?</p>
      </div>
      <div class="modal-footer">
        <form action="{% url "reports:delete_report" report.id %}" method="post" class="form">
          {% csrf_token %}
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
          <button type="submit" class="btn btn-danger">Да, удалить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block additional_scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>
<script type="module" src="{% static "assets/js/get_updated_date.js" %}"></script>
{% endblock  %}