LAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('user.urls', namespace='user')),
    path('pupils/', include('pupils.urls', namespace='pupils')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('reports/', include('reports.urls', namespace='reports')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.view_404'
handler403 = 'main.views.view_403'
handler500 = 'main.views.view_500'

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from user import views

app_name = 'user'

urlpatterns = [
    path('', views.UserProfile.as_view(), name='profile'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='user/password_reset_form.html', 
        email_template_name='user/password_reset_email.html',
        success_url=reverse_lazy('user:password_reset_done')
        ), 
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')
        ), 
        name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    """Модель описания пользователя"""
    def __str__(self):
        return self.email
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'
        ordering = ('id',)
        

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(label='Подтверди пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтверди пароль'}))
    

user/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.contrib.auth.mixins import LoginRequiredMixin

from user.forms import UserLoginForm, UserPasswordChangeForm


class UserLogin(LoginView):
    """Класс представления для авторизации пользователя"""
    template_name = 'user/login.html'
    form_class = UserLoginForm
    extra_context = {'title': 'L.A.S - Войти',}


class UserProfile(LoginRequiredMixin, TemplateView):
    """Класс представления для отображения профиля пользователя"""
    template_name = 'user/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserPasswordChangeForm(user=self.request.user)
        context['title'] = 'L.A.S - Профиль'
        return context
    

class UserPasswordChange(LoginRequiredMixin, PasswordChangeView):
    """Класс представления для смены пароля пользователя"""
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('user:profile')
    template_name = 'user/profile.html'

user/templates/user/login.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block content %}
<div class="row justify-content-center">
  <section class="section col-lg-6 col-sm-12">
    <h2 class="section__h2 text-center text-uppercase">Вход</h2>
    <form action="{% url "user:login" %}" method="post" class="form">
      {% csrf_token %}
      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
      {% endif %}

      {% draw_form form %}

      {% comment %} <div class="form-floating form__item">
        <input type="text" class="form-control" id="id_username" placeholder="name@example.com" name="username" required>
        <label for="id_username">Email</label>
      </div>
      <div class="form-floating form__item">
        <input type="password" class="form-control" id="id_password" placeholder="Пароль" name="password" required>
        <label for="id_password">Пароль</label>
      </div>
      
      {% if form.errors %}
        <div class="form__errors">
          {% for field, errors in form.errors.items  %}
            {% for error in errors %}
                <p>{{ error }}</p>
            {% endfor %}
          {% endfor %}
        </div>
      {% endif %} {% endcomment %}
      
      <div class="form__item text-center">
        <button class="btn btn-primary" type="submit">Войти</button>
      </div>
      <a href="{% url "user:password_reset" %}">Забыли пароль?</a>
    </form>
  </section>
</div>

{% endblock %}

user/templates/user/password_reset_complete.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2">Пароль успешно изменён</h2>
    <p class="section__text"><a href="{% url "user:login" %}">Войти</a></p>
  </section>
</div>

{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="row">
  <section class="section">
    <h3 class="section__h3">Изменить пароль</h3>
    <form method="post" class="form">
      {% csrf_token %}
      <div class="form-floating form__item">
        <input type="password" class="form-control" id="id_new_password1" placeholder="Новый пароль" name="new_password1" required>
        <label for="id_new_password1">Новый пароль</label>
      </div>
      <div class="form-floating form__item">
        <input type="password" class="form-control" id="id_new_password2" placeholder="Подтверди пароль" name="new_password2" required>
        <label for="id_new_password2">Подтверди пароль</label>
      </div>

      {% if form.errors %}
        <div class="form__errors">
          {% for field, errors in form.errors.items  %}
            {% for error in errors %}
                <p>{{ error }}</p>
            {% endfor %}
          {% endfor %}
        </div>
      {% endif %}
      
      <div class="form__item">
        <button class="btn btn-primary" type="submit">Изменить</button>
      </div>
    </form>
  </section>
</div>

{% endblock %}

user/templates/user/password_reset_done.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2">Восстановления пароля</h2>
    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
  </section>
</div>
{% endblock %}

user/templates/user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

user/templates/user/password_reset_form.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2">Забыли пароль?</h2>
    <form method="post" class="form">
      {% csrf_token %}
      <div class="form-floating form__item">
        <input type="email" class="form-control" id="id_email" placeholder="name@example.com" name="email" required>
        <label for="id_email">Email</label>
      </div>
      <div class="form__item">
        <button class="btn btn-primary" type="submit">Восстановить</button>
      </div>
    </form>
  </section>
</div>
{% endblock %}

user/templates/user/profile.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2">Профиль</h2>
    <p class="section__text">Добро пожаловать, {{ user }}</p>
    <h3 class="section__h3">Изменить пароль</h3>
    <form action="{% url "user:password_change" %}" method="post" class="form">
      {% csrf_token %}

      {% draw_form form %}
      {% comment %} <div class="form-floating form__item">
        <input type="password" class="form-control" id="id_old_password" placeholder="Старый пароль" name="old_password" required>
        <label for="id_old_password">Старый пароль</label>
      </div>
      <div class="form-floating form__item">
        <input type="password" class="form-control" id="id_new_password1" placeholder="Новый пароль" name="new_password1" required>
        <label for="id_new_password1">Новый пароль</label>
      </div>
      <div class="form-floating form__item">
        <input type="password" class="form-control" id="id_new_password2" placeholder="Подтверди пароль" name="new_password2" required>
        <label for="id_new_password2">Подтверди пароль</label>
      </div>

      {% if form.errors %}
        <div class="form__errors">
          {% for field, errors in form.errors.items  %}
            {% for error in errors %}
                <p>{{ error }}</p>
            {% endfor %}
          {% endfor %}
        </div>
      {% endif %} {% endcomment %}
      
      <div class="form__item">
        <button class="btn btn-primary" type="submit">Изменить</button>
      </div>
    </form>
  </section>
</div>

{% endblock %}