LAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('user.urls', namespace='user')),
    path('pupils/', include('pupils.urls', namespace='pupils')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('reports/', include('reports.urls', namespace='reports')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.view_404'
handler403 = 'main.views.view_403'
handler500 = 'main.views.view_500'

lessons/urls.py
from django.urls import path

from lessons import views

app_name = 'lessons'

urlpatterns = [
    path('', views.LessonsListView.as_view(), name='lessons_list'),
    path('create-lesson/', views.CreateLessonView.as_view(), name='create_lesson'),
    path('update-lesson/<int:lesson_id>/', views.UpdateLessonView.as_view(), name='update_lesson'),
    path('delete-lesson/<int:lesson_id>/', views.DeleteLessonView.as_view(), name='delete_lesson'),
    path('get-lesson-datetime/<int:lesson_id>/', views.GetLessonDatetime.as_view(), name='get_lesson_datetime')
]

pupils/urls.py
from django.urls import path

from pupils import views

app_name = 'pupils'

urlpatterns = [
    path('', views.PupilsListView.as_view(), name='pupils_list'),
    path('create-pupil/', views.CreatePupilView.as_view(), name='create_pupil'),
    path('update-pupil/<int:pupil_id>/', views.UpdatePupilView.as_view(), name='update_pupil'),
    path('get-pupil-price/<int:pupil_id>/', views.GetPupilPrice.as_view(), name='get_pupil_price')
]

reports/urls.py
from django.urls import path

from reports import views

app_name = 'reports'

urlpatterns = [
    path('', views.ReportsListView.as_view(), name='reports_list'),
    path('create-report/', views.CreateReportView.as_view(), name='create_report'),
    path('read-report/<int:report_id>/', views.ReadReportView.as_view(), name='read_report'),
    path('update-report/<int:report_id>/', views.UpdateReportView.as_view(), name='update_report'),
    path('delete-report/<int:report_id>/', views.DeleteReportView.as_view(), name='delete_report'),
    path('get-report-period/<int:report_id>/', views.GetReportPeriod.as_view(), name='get_report_period'),
    path('save-report-as-pdf/<int:report_id>/', views.SaveReportAsPdf.as_view(), name='save_report_as_pdf'),
    path('save-report-as-png/<int:report_id>/', views.SaveReportAsPng.as_view(), name='save_report_as_png'),
]

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from user import views

app_name = 'user'

urlpatterns = [
    path('', views.UserProfile.as_view(), name='profile'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='user/password_reset_form.html', 
        email_template_name='user/password_reset_email.html',
        success_url=reverse_lazy('user:password_reset_done')
        ), 
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')
        ), 
        name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "assets/fontawesome/css/fontawesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/fontawesome/css/brands.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/fontawesome/css/solid.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    {% block additional_styles %}{% endblock  %}
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <title>{{ title }}</title>
</head>
<body>
    <header class="header">
        <nav class="menu navbar navbar-expand-lg">
            <div class="container">
              <a class="navbar-brand menu__brand" href="/">L.A.S</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Меню</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    {% if user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link menu__link" href="{% url "pupils:pupils_list" %}"><i class="fa-regular fa-user icon"></i>Ученики</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link menu__link" href="{% url "lessons:lessons_list" %}"><i class="fa-regular fa-book icon"></i>Уроки</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link menu__link" href="{% url "reports:reports_list" %}"><i class="fa-regular fa-calendar-days icon"></i>Отчёты</a>
                      </li>
                      {% if user.is_admin or user.is_staff %}
                        <li class="nav-item">
                          <a class="nav-link menu__link" href="{% url "admin:index" %}"><i class="fa-solid fa-gear icon"></i>Админка</a>
                        </li>
                      {% endif %}
                      <li class="nav-item">
                        <a class="nav-link menu__link" href="{% url "user:profile" %}"><i class="fa-regular fa-circle-user icon"></i>Профиль</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link menu__link" href="{% url "user:logout" %}"><i class="fa-solid fa-arrow-right-from-bracket icon"></i>Выход</a>
                      </li>
                    {% else %}
                      <li class="nav-item">
                        <a class="nav-link menu__link" href="{% url "user:login" %}"><i class="fa-solid fa-arrow-right-to-bracket icon"></i>Вход</a>
                      </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </nav>
    </header>

    <main class="content">
      <div class="container">
        {% block content %}
        
        {% endblock  %}
      </div>
    </main>

    <footer class="footer">
      <div class="container">
        <div class="row">
          <p class="footer__text text-center">&copy; L.A.S by justP</p>
        </div>
      </div>
    </footer>
    <script src="{% static "assets/js/bootstrap.bundle.min.js" %}"></script>
    {% block additional_scripts %}{% endblock  %}
    <script type="module" src="{% static "assets/js/main.js" %}"></script>
</body>
</html>