LAS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('user.urls', namespace='user')),
    path('pupils/', include('pupils.urls', namespace='pupils')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('reports/', include('reports.urls', namespace='reports')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.view_404'
handler403 = 'main.views.view_403'
handler500 = 'main.views.view_500'

lessons/urls.py
from django.urls import path

from lessons import views

app_name = 'lessons'

urlpatterns = [
    path('', views.LessonsListView.as_view(), name='lessons_list'),
    path('create-lesson/', views.CreateLessonView.as_view(), name='create_lesson'),
    path('update-lesson/<int:lesson_id>/', views.UpdateLessonView.as_view(), name='update_lesson'),
    path('delete-lesson/<int:lesson_id>/', views.DeleteLessonView.as_view(), name='delete_lesson'),
    path('get-lesson-datetime/<int:lesson_id>/', views.GetLessonDatetime.as_view(), name='get_lesson_datetime')
]

lessons/models.py
import locale

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

from pupils.models import Pupil

from subjects.models import Subjects


locale.setlocale(locale.LC_ALL, ('ru_RU', 'UTF-8')) # установка локали для отображения даты на русском


class LessonQuerySet(models.QuerySet):
    def total_money(self):
        return sum(lesson.money_recived for lesson in self)


class Lesson(models.Model):
    pupil = models.ForeignKey(verbose_name='Ученик',
                              to=Pupil,
                              on_delete=models.CASCADE,
                              related_name='pupil'
                              )
    
    subject = models.ForeignKey(verbose_name='Предмет',
                                to=Subjects,
                                on_delete=models.CASCADE,
                                related_name='subject'
                                )
    
    lesson_datetime = models.DateTimeField(verbose_name='Дата проведения урока',
                                    auto_now_add=False,
                                    unique=True
                                    )
    
    lesson_duration = models.DecimalField(verbose_name='Продолжительность урока', 
                                          decimal_places=2, 
                                          max_digits=3,
                                          default=1,
                                          validators=(MinValueValidator(1, 'Слишком короткий урок'),
                                                      MaxValueValidator(2, 'Слишком долгий урок'))
                                        )
    
    money_recived = models.DecimalField(verbose_name='Денег заработано', 
                                        decimal_places=2, 
                                        max_digits=7,
                                        default=0
                                        )
    
    objects = LessonQuerySet.as_manager()
    
    def __str__(self):
        return f"Урок с учеником: {self.pupil}; По предмету: {self.subject}; За {self.lesson_datetime.strftime('%d %b %Y %H:%M')}"
    
    def get_absolute_url(self):
        return reverse("lessons:update_lesson", kwargs={"lesson_id": self.pk})
    

    class Meta:
        db_table = 'lessons'
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'
        ordering = ('-lesson_datetime', '-id')
    

lessons/forms.py
from django import forms

from lessons.models import Lesson

from pupils.models import Pupil


class LessonsFilterForm(forms.ModelForm):
    """Класс формы фильтрации уроков"""
    lesson_date = forms.DateField(
        required=False, 
        label='Дата проведения урока', 
        widget=forms.DateInput(
            attrs={
                'class': 'form-control', 
                'type': 'date', 
                'placeholder': '08-09-2024'
            }
        )
    )

    class Meta:
        model = Lesson
        fields = ('pupil', 'subject')
        widgets = {
            'pupil': forms.Select(attrs={'class': 'form-select'}),
            'subject': forms.Select(attrs={'class': 'form-select'}),
        }
    
    def __init__(self, *args, **kwargs):
        # так как в форме нельзя получить доступ к текущему пользователю, то его нужно явно передать в конструктор в коллекции kwargs
        self.user = kwargs.pop('user', None) 
        super(LessonsFilterForm, self).__init__(*args, **kwargs)

        self.fields['pupil'].queryset = Pupil.objects.filter(owner=self.user, is_active=True)
        self.fields['pupil'].empty_label = 'Выбери ученика'
        self.fields['pupil'].required = False

        self.fields['subject'].empty_label = 'Выбери предмет'
        self.fields['subject'].required = False



class CreateLessonForm(forms.ModelForm):
    """Класс формы создания урока"""
    class Meta:
        model = Lesson
        fields = '__all__'
        widgets = {
            'pupil': forms.Select(attrs={'class': 'form-select'}),
            'subject': forms.Select(attrs={'class': 'form-select'}),
            'lesson_datetime': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local', 'placeholder': '08-09-2024 12:00'}),
            'lesson_duration': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.5', 'min': 0.5, 'max': 2}),
            'money_recived': forms.NumberInput(attrs={'class': 'form-control'}),

        }
    
    def __init__(self, *args, **kwargs):
        # так как в форме нельзя получить доступ к текущему пользователю, то его нужно явно передать в конструктор в коллекции kwargs
        self.user = kwargs.pop('user', None) 
        super(CreateLessonForm, self).__init__(*args, **kwargs)

        self.fields['pupil'].queryset = Pupil.objects.filter(owner=self.user, is_active=True)
        self.fields['pupil'].empty_label = 'Выбери ученика'

        self.fields['subject'].empty_label = 'Выбери предмет'


class UpdateLessonForm(forms.ModelForm):
    """Класс формы обновления данных урока"""
    class Meta:
            model = Lesson
            fields = '__all__'
            widgets = {
                'pupil': forms.Select(attrs={'class': 'form-select'}),
                'subject': forms.Select(attrs={'class': 'form-select'}),
                'lesson_datetime': forms.DateTimeInput(attrs={'class': 'form-control datetime-updater', 
                                                              'type': 'datetime-local', 
                                                              'placeholder': '2024-08-09 12:00'}),
                'lesson_duration': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.5', 'min': 0.5, 'max': 2}),
                'money_recived': forms.NumberInput(attrs={'class': 'form-control'}),
            }
        
    def __init__(self, *args, **kwargs):
        # так как в форме нельзя получить доступ к текущему пользователю, то его нужно явно передать в конструктор в коллекции kwargs
        self.user = kwargs.pop('user', None) 
        super(UpdateLessonForm, self).__init__(*args, **kwargs)

        self.fields['pupil'].queryset = Pupil.objects.filter(owner=self.user, is_active=True)
        self.fields['pupil'].empty_label = 'Выбери ученика'

        self.fields['subject'].empty_label = 'Выбери предмет'

lessons/views.py
from django.urls import reverse_lazy
from django.http import Http404, JsonResponse
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from lessons.models import Lesson

from lessons.forms import LessonsFilterForm, CreateLessonForm, UpdateLessonForm

from user.utils import verify_owner


class LessonsListView(LoginRequiredMixin, ListView):
    """Класс представления для страницы со списком уроков"""
    template_name = 'lessons/lessons_list.html'
    context_object_name = 'lessons'
    paginate_by = 5

    def get_queryset(self):
        
        lessons = Lesson.objects.filter(pupil__owner=self.request.user).select_related('pupil', 'subject')

        pupil = self.request.GET.get('pupil', None)

        lesson_date = self.request.GET.get('lesson_date', None)

        subject = self.request.GET.get('subject', None)

        if pupil:
            lessons = lessons.filter(pupil__id=pupil)

        if lesson_date:
            lessons = lessons.filter(lesson_datetime__date=lesson_date)

        if subject:
            lessons = lessons.filter(subject__id=subject)

        return lessons
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # при создании формы передаём в неё пользователя
        context['form'] = LessonsFilterForm(data=self.request.GET, user=self.request.user) 
        context['title'] = 'L.A.S - Уроки'
        return context


class CreateLessonView(LoginRequiredMixin, CreateView):
    """Класс представления для страницы создания урока"""
    template_name = 'lessons/create_lesson.html'
    model = Lesson
    form_class = CreateLessonForm
    success_url = reverse_lazy('lessons:lessons_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'L.A.S - Создать урок'
        return context
    
    def get_form_kwargs(self):
        kwargs = super(CreateLessonView, self).get_form_kwargs()
        # при создании формы передаём в неё пользователя
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        return super().form_valid(form)


class UpdateLessonView(LoginRequiredMixin, UpdateView):
    """Класс представления для страницы обновления данных урока"""
    template_name = 'lessons/update_lesson.html'
    form_class = UpdateLessonForm
    model = Lesson
    context_object_name = 'lesson'
    pk_url_kwarg = 'lesson_id'
    
    def get_object(self, lesson_id=None, queryset=None):
        try:
            if lesson_id is None:
                lesson_id = self.kwargs.get(self.pk_url_kwarg)

            lesson = Lesson.objects.get(pk=lesson_id)
            
        except Lesson.DoesNotExist:
            lesson = None
        finally:
            return lesson
    
    def get(self, request, lesson_id, *args, **kwargs):
        lesson = self.get_object(lesson_id)

        if lesson is not None:
            if verify_owner(lesson.pupil.owner, self.request.user):
                return super().get(request, lesson_id, *args, **kwargs)
            else:
                raise PermissionDenied()
        raise Http404()
    
    def post(self, request, lesson_id, *args, **kwargs):
        lesson = self.get_object(lesson_id)

        if lesson is not None:
            if verify_owner(lesson.pupil.owner, self.request.user):
                return super().post(request, lesson_id, *args, **kwargs)
            else:
                raise PermissionDenied()
        raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'L.A.S - Обновить данные урока'
        return context
    
    def get_form_kwargs(self):
        kwargs = super(UpdateLessonView, self).get_form_kwargs()
        # при создании формы передаём в неё пользователя
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        return super().form_valid(form)


class DeleteLessonView(LoginRequiredMixin, DeleteView):
    """Класс представления для удаления урока"""
    model = Lesson
    success_url = reverse_lazy('lessons:lessons_list')
    pk_url_kwarg = 'lesson_id'

    def get_object(self, lesson_id=None, queryset=None):
        try:
            if lesson_id is None:
                lesson_id = self.kwargs.get(self.pk_url_kwarg)

            lesson = Lesson.objects.get(pk=lesson_id)
            
        except Lesson.DoesNotExist:
            lesson = None
        finally:
            return lesson
    
    def post(self, request, lesson_id, *args, **kwargs):
        lesson = self.get_object(lesson_id)

        if lesson is not None:
            if verify_owner(lesson.pupil.owner, self.request.user):
                return super().post(request, lesson_id, *args, **kwargs)
            else:
                raise PermissionDenied()
        raise Http404()
    

class GetLessonDatetime(LoginRequiredMixin, View):
    """Класс представления для получения даты проведения урока"""
    def get_object(self, lesson_id=None, queryset=None):
        try:
            if lesson_id is None:
                lesson_id = self.kwargs.get(self.pk_url_kwarg)

            lesson = Lesson.objects.get(pk=lesson_id)
            
        except Lesson.DoesNotExist:
            lesson = None
        finally:
            return lesson
    
    def get(self, request, lesson_id):
        lesson = self.get_object(lesson_id)

        if lesson is not None:
            response_data = {'lesson_datetime': lesson.lesson_datetime}

            return JsonResponse(response_data)
        else:
            raise Http404()

lessons/templates/lessons/create_lesson.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block additional_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock  %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2 text-center">Добавить урок</h2>
    <form action="{% url "lessons:create_lesson" %}" method="post" class="form">
      {% csrf_token %}
      {% draw_form form %}
      <div class="form__item text-center">
        <button class="btn btn-success" type="submit">Добавить</button>
      </div>
    </form>
  </section>
</div>
{% endblock %}

{% block additional_scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>
<script src="{% static "assets/js/datetimepikers.js" %}"></script>
<script type="module" src="{% static "assets/js/change_money_recived.js" %}"></script>
{% endblock  %}

lessons/templates/lessons/lessons_list.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block additional_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock  %}

{% block content %}
<div class="row">
  <div class="col-lg-3 col-sm-12">
    <div class="offcanvas-lg offcanvas-start" tabindex="-1" id="filter" aria-labelledby="filterLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#filter"
          aria-label="Close"></button>
      </div>
      <div class="offcanvas-body flex-column">
        <h3>Фильтр</h3>
        <form action="{% url "lessons:lessons_list" %}" method="get" class="form">
          {% draw_form form %}
          <div class="form__item text-center">
            <button class="btn btn-primary" type="submit">Применить</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col-lg-9 col-sm-12">
    <h2>Список уроков</h2>
    <div class="togglers">
      <a href="{% url "lessons:create_lesson" %}" class="btn btn-success"><i class="fa-solid fa-plus"></i> Добавить</a>
      <button data-bs-toggle="offcanvas" data-bs-target="#filter" role="button" class="btn btn-secondary btn_filter"
        aria-controls="filter"><i class="fa-solid fa-filter"></i> Фильтр</button>
    </div>
    <div class="cards row g-3">
      {% if lessons %}
        {% for lesson in lessons %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ lesson.pupil }}</h5>
              <p class="card-text">Денег заработано: {{ lesson.money_recived|floatformat }} руб</p>
              <p class="card-text">Дата проведения: {{ lesson.lesson_datetime }}</p>
              <p class="card-text">Времени затрачено: {{ lesson.lesson_duration|floatformat }} час{{ lesson.lesson_duration|pluralize:'а' }}</p>
              <div class="subjects">
                <p class="subjects__text fw-bold">Предмет</p>
                <span class="badge text-bg-primary">{{ lesson.subject }}</span>
              </div>
              <a href="{{ lesson.get_absolute_url }}" class="card-link">Редактировать</a>
            </div>
          </div>
        {% endfor %}
        
        {% pagination page_obj paginator %}
        
      {% else %}
          <h3>Ничего не найдено!</h3>
      {% endif %}
      
    </div>
  </div>
</div>
{% endblock %}

{% block additional_scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>
<script src="{% static "assets/js/datepikers.js" %}"></script>
{% endblock  %}

lessons/templates/lessons/update_lesson.html
{% extends "base.html" %}

{% load static %}

{% load service_tags %}

{% block additional_styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock  %}

{% block content %}
<div class="row">
  <section class="section">
    <h2 class="section__h2 text-center">Обновить данные урока</h2>
    <form action="{% url "lessons:update_lesson" lesson.id %}" method="post" class="form">
      {% csrf_token %}
      {% draw_form form %}
      <div class="form__item text-center">
        <button class="btn btn-primary" type="submit">Обновить</button>
      </div>
    </form>
  </section>

  <section class="section">
    <h2 class="section__h2">Удалить урок</h2>
    <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteLesson" role="button">Удалить</button>
  </section>
</div>

<div class="modal fade" id="deleteLesson" tabindex="-1" aria-labelledby="deleteLessonLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteLessonLabel">Удалить урок</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Вы действительно хотите удалить {{ lesson }}?</p>
      </div>
      <div class="modal-footer">
        <form action="{% url "lessons:delete_lesson" lesson.id %}" method="post" class="form">
          {% csrf_token %}
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
          <button type="submit" class="btn btn-danger">Да, удалить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block additional_scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>
<script type="module" src="{% static "assets/js/get_updated_datetime.js" %}"></script>
<script type="module" src="{% static "assets/js/change_money_recived.js" %}"></script>
{% endblock  %}